const posts = [
  {
    type: 'MENU_POST',
    image: require('@assets/feed-assets/chickenchester.png'),
    user: 'Chicken Chester',
    verfied: false,
    menuType: 'Cafe & Restaurant',
    date: '2 day ago',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sem eget nunc rutrum rutrum.',
    images: [require('@assets/feed-assets/restaurantimg.png')],
    likes: 32000,
    commentCount: 597,
    shares: 12300,
    comments: [
      {
        user: 'Jaxson Schleifer',
        image: require('@assets/feed-assets/jaxson.png'),
        text: 'Lorem ipsum ',
        date: '1h',
        likes: 2,
      },
    ],
  },
  {
    type: 'SHARED_MENU',
    image: require('@assets/feed-assets/rayna.png'),
    user: 'Rayna Rosser',
    verified: true,
    menuImg: require('@assets/feed-assets/macimg.png'),
    menu: 'Chicken MACDO, Carmel Sandae,Fries, and Large pepsi',
    menuType: `Mcdonalds's`,
    date: '2 day ago',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sem eget nunc rutrum rutrum.',
    images: [
      require('@assets/feed-assets/mac1.png'),
      require('@assets/feed-assets/mac2.png'),
      require('@assets/feed-assets/mac3.png'),
    ],
    likes: 32000,
    commentCount: 597,
    shares: 12300,
    comments: [],
  },
  {
    type: 'SHARED_POST',
    image: require('@assets/feed-assets/skylarani.png'),
    user: 'Skylarani Arcand',
    verified: false,
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sem eget nunc rutrum rutrum.',
    date: '1 sec ago',
    post: {
      type: 'SHARED_MENU',
      image: require('@assets/feed-assets/rayna2.png'),
      user: 'Rayna Rosser',
      verified: true,
      menuImg: require('@assets/feed-assets/chickenchester.png'),
      menu: 'Buy 2 Chicken Burget Combo and 2 Cheesy sticks',
      menuType: `Chicken Chester`,
      date: '2 day ago',
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed sem eget nunc rutrum rutrum.',
      images: [require('@assets/feed-assets/restaurantimg.png')],
    },

    likes: 32000,
    commentCount: 597,
    shares: 12300,
    comments: [],
  },
];
export default posts;
